### ISSUE TITLE
Does not run. 

### ISSUE THREAD

**Issue by chaunceychason** [themantalope/pydendroheatmap#10]
There is a print statement that reads,   print(""" 
and needs python3 compatibility.

... this wont run, and the fundtion says pydendroheatmap has no attributeDendroHeatMap even though I know it does.

**Comment by themantalope** [comment]
Can you point out the line please? I think this was an issue in the past that was fixed.

**Comment by themantalope** [comment]
@chaunceychason hey I fixed line [174](https://github.com/themantalope/pydendroheatmap/blob/1a85f0379d482d7c5162835da920777d025fc4c9/pydendroheatmap/pydendroheatmap.py#L174). Let me know if that was the problem.

**Comment by chaunceychason** [comment]
Im not sure what could be causing this problem, it could be a python
compatibility issue, but when try to access any functions after importing
pydendroheatmap as pdh, it doesnt work. It is unable to find any
attributes. I just did a clean install and got this.


Attached the error.

**Comment by themantalope** [comment]
@chaunceychason can you copy and paste the output when you get an error? I don't see any attachment.

**Comment by themantalope** [comment]
I am able to `import` the module with no issues on my machine which is running python 3.6.

**Comment by chaunceychason** [comment]
Okay. Well. I provided a screenshot. I can provide the text too.. The issue
is that it cant acccess the internal functions. I am able to import with no
problem. It is when I try to call pdh.Dendro.... it just fails and says no
attribute named DendroHeatMap.

I also tried to run it in a python 2.7 environment and got the same error,
so like you said, it isnt related to the python version.


*import* *pydendroheatmap* *as* *pdh*


In [*2*]: pdh

Out[*2*]: <module 'pydendroheatmap' from
'/Users/nicholaschason/anaconda3/lib/python3.6/site-packages/pydendroheatmap-1.4-py3.6.egg/pydendroheatmap/__init__.py'>


In [*3*]: pdh.Den


Notive the pdh.Den... doesnt autocomplete showing there are no available
attributes.

**Comment by chaunceychason** [comment]
Hi, sorry for the double email. I just wanted to add, that I tried to load
the module attribute directly (based on this:
https://www.stefaanlippens.net/python-pickling-and-dealing-with-attributeerror-module-object-has-no-attribute-thing.html)
 but
that also failed with the following error:

*import* *pydendroheatmap* *as* *pdh*


In [*2*]: *from* *pydendroheatmap* *import* DendroHeatMap

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-2-a54f1ea6375c> in <module>()

----> 1 from pydendroheatmap import DendroHeatMap


ImportError: cannot import name 'DendroHeatMap'

**Comment by themantalope** [comment]
I got rid of several files in the repo that may have been causing problems. I have also updated the `pypi` repository, which was several versions of the code behind what is on the github repository.

Please try to upgrade or reinstall the package via `pip`. You can do this by running either:
```bash
pip uninstall pydendroheatmap
pip install pydendroheatmap
```
or
```bash
pip install -U pydendroheatmap
```

Please let me know if those change fix the errors you are getting.

In the future, please do not use the email interface to communicate regarding a repository issue. It's better and easier to format your response directly on the "Issues" tab for the GitHub repository. Additionally, I can't see any of your attachments on either the email chain or via GitHub's issue page.  You can review the GitHub format styling page for markdown [here](https://guides.github.com/features/mastering-markdown/).

Finally, when you are bringing issues up on a repository, you **must** provide some code and the exact error. To be honest, I still don't completely understand what your problem has been because you have not pasted any error messages.  Additionally, while autocomplete failures may be an indication that something is not working, it's not a reliable measure to know if something is wrong because it could potentially be due to the way autocomplete is configured on your machine.

**Comment by chaunceychason** [comment]
You don't have to be a jackass about it. I couldn't send straight from
GitHub at the time so I sent an email, and if you couldn't see my
attachments then ask nicely and I'd happily send them to you in whatever
format you want. You code was broke and I was just letting you know. In the
future don't be a dick.

**Comment by themantalope** [comment]
I apologize if you felt that I wasn't polite, but I did my best to help you out. I couldn't understand what the problem was with the code.

I was simply providing suggestions.

Did the fixes resolve the issues you were having with the code?
