### ISSUE TITLE
proper citation of work on a forked repo

### ISSUE THREAD

**Issue by themantalope** [themantalope/pydendroheatmap#2]
Hi @kaniblu, hope you get this message. I appreciate the additions you have made to the pydendroheatmap repo. However there were a couple of things that I wanted to ask you about, and I wasn't able to find any other method of contacting you.

1) I saw that in the new repo documentation file you removed the last line about the contributions of Nathan Salomonis. While it's not legally necessary to cite him or give any credit for the work that he did, much of the code originally came from his post with some minor tweaking. I feel that it is unfair to remove that acknowledgement on the repo page.

2) If you would like to add in your contributions to the original project you are more than welcome. I like how you added more functionality for the colormaps and the cluster analysis. However, the name you gave for your pip package is very close to the original one, and it may cause confusion. Thus I would ask you to either (a) add your contributions to the original project so that they may be distributed under pydendroheatmap or (b) give your package a different name so that folks will not confuse the two, and give the original project author (me) acknowledgement for their work. In addition, if you are going to keep your own repo for the forked project, please make sure that it is able to accept its own issues as right now issues that pertain to your version of the code will appear as issues for this repo (pydendroheatmap).

If you have any questions or need anything from me, let me know!

-themantalope

**Comment by themantalope** [comment]
@themantalope

**Comment by kaniblu** [comment]
Sorry for the late reply. I should have gotten a notification email before, but somehow I wasn't aware of this issue until I randomly stumbled upon Github notification page. My deep apologies. 

You make a very good point, and I fully understand your concern about the acknowledge issue here. As you can see from my issue history, I indeed attempted to contribute to your project as I needed. But the attempt soon seemed dire when there were so many features and requirements that I had to meet, so the only choice left for me to do was fork your project and start working on my own. I was not trying to start a whole new project; all I wanted to achieve was making a library that draws customized dendroheatmap for my own needs. It is indeed my mistake to remove the original author's contributions in the comments and I can assure you that it wasn't intentional at all. The uploaded pip package was created for my own convenience as well. 

Although I am not working on this project anymore, I will fix the issues right away. Sorry for the unnecessary confusion.

Have a good day!
Kang Min Yoo.

**Comment by themantalope** [comment]
Hi Kang Min,

Not a problem. I just wanted to make sure that other users who were downloading the packages didn't get confused by the two implementations. Thanks for the follow up. I just wanted to make sure that you had considered these potential issues! 

-Matt
